### ISSUE TITLE
GitHub Blog URLs incorrectly redirecting

### ISSUE THREAD

**Issue by jfelchner** [hbang/LinkOpener#22]
Github's blog URLs redirect to ioctocat and they should not.

https://github.com/blog

**Comment by kirb** [comment]
I'm not sure what should be done regarding GitHub links that iOctocat doesn't actually natively open, because in one way it might not be useful because it just shows a web view anyway, but it could be implemented in future. Plus, you do end up seeing the content anyway, even despite the jump to another app to do what your browser could have done.

Probably I'll just resolve it by working out what paths it doesn't support and just keep a static list of it like I do for Twitter.

**Comment by jfelchner** [comment]
The blog URLs aren't actually even opening for me in ioctocat. 😕

**Comment by jfelchner** [comment]
Any https://github.com/blog/* URL opens a blank web view.

**Comment by iAdam1n** [comment]
Was an ioctocat bug that is fixed.
